// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

type Observation struct {
	SeriesID int64 `db:"series_id"`
	Ts       int64 `db:"ts"`
	Count    int64 `db:"count"`
}

type Series struct {
	ID      int64  `db:"id"`
	Source  string `db:"source"`
	Repo    string `db:"repo"`
	Release string `db:"release"`
	Asset   string `db:"asset"`
	Os      string `db:"os"`
	Arch    string `db:"arch"`
	Format  string `db:"format"`
}
