// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbsqlc

import (
	"context"
)

const anchorObservation = `-- name: AnchorObservation :one
SELECT ts, count
FROM observations
WHERE series_id = ?1 AND ts <= ?2
ORDER BY ts DESC
LIMIT 1
`

type AnchorObservationParams struct {
	SeriesID int64 `db:"series_id"`
	Ts       int64 `db:"ts"`
}

type AnchorObservationRow struct {
	Ts    int64 `db:"ts"`
	Count int64 `db:"count"`
}

// The last observation at or before `ts`, i.e. the value a step line carries
// into the start of a query window.
func (q *Queries) AnchorObservation(ctx context.Context, arg AnchorObservationParams) (AnchorObservationRow, error) {
	row := q.db.QueryRowContext(ctx, anchorObservation, arg.SeriesID, arg.Ts)
	var i AnchorObservationRow
	err := row.Scan(&i.Ts, &i.Count)
	return i, err
}

const countSeries = `-- name: CountSeries :one
SELECT count(*) FROM series
`

func (q *Queries) CountSeries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSeries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertObservation = `-- name: InsertObservation :exec
INSERT INTO observations (series_id, ts, count)
VALUES (?, ?, ?)
ON CONFLICT (series_id, ts) DO NOTHING
`

type InsertObservationParams struct {
	SeriesID int64 `db:"series_id"`
	Ts       int64 `db:"ts"`
	Count    int64 `db:"count"`
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) error {
	_, err := q.db.ExecContext(ctx, insertObservation, arg.SeriesID, arg.Ts, arg.Count)
	return err
}

const latestCount = `-- name: LatestCount :one
SELECT count
FROM observations
WHERE series_id = ?
ORDER BY ts DESC
LIMIT 1
`

func (q *Queries) LatestCount(ctx context.Context, seriesID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestCount, seriesID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSeries = `-- name: ListSeries :many
SELECT id, source, repo, release, asset, os, arch, format
FROM series
WHERE (source = ?1 OR ?1 = '')
  AND (repo = ?2 OR ?2 = '')
ORDER BY id
`

type ListSeriesParams struct {
	Source string `db:"source"`
	Repo   string `db:"repo"`
}

// Series matching optional source/repo filters (pass ” to match all). Used by
// both /api/series and the timeseries aggregation.
func (q *Queries) ListSeries(ctx context.Context, arg ListSeriesParams) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listSeries, arg.Source, arg.Repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Repo,
			&i.Release,
			&i.Asset,
			&i.Os,
			&i.Arch,
			&i.Format,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rangeObservations = `-- name: RangeObservations :many
SELECT ts, count
FROM observations
WHERE series_id = ?1
  AND ts > ?2
  AND ts <= ?3
ORDER BY ts
`

type RangeObservationsParams struct {
	SeriesID int64 `db:"series_id"`
	FromTs   int64 `db:"from_ts"`
	ToTs     int64 `db:"to_ts"`
}

type RangeObservationsRow struct {
	Ts    int64 `db:"ts"`
	Count int64 `db:"count"`
}

// Observations strictly after `from` and at or before `to`, in time order.
func (q *Queries) RangeObservations(ctx context.Context, arg RangeObservationsParams) ([]RangeObservationsRow, error) {
	rows, err := q.db.QueryContext(ctx, rangeObservations, arg.SeriesID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RangeObservationsRow
	for rows.Next() {
		var i RangeObservationsRow
		if err := rows.Scan(&i.Ts, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSeries = `-- name: UpsertSeries :one
INSERT INTO series (source, repo, release, asset, os, arch, format)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (source, repo, release, asset)
    DO UPDATE SET source = excluded.source
RETURNING id
`

type UpsertSeriesParams struct {
	Source  string `db:"source"`
	Repo    string `db:"repo"`
	Release string `db:"release"`
	Asset   string `db:"asset"`
	Os      string `db:"os"`
	Arch    string `db:"arch"`
	Format  string `db:"format"`
}

// Get the id of a series, creating it if new. The no-op DO UPDATE lets
// RETURNING return the existing row's id on conflict (SQLite can't RETURN from
// a bare DO NOTHING).
func (q *Queries) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (int64, error) {
	row := q.db.QueryRowContext(
		ctx, upsertSeries,
		arg.Source,
		arg.Repo,
		arg.Release,
		arg.Asset,
		arg.Os,
		arg.Arch,
		arg.Format,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
